language: java
jdk:
  - openjdk11

branches:
  only:
    - master

# gradlew에 대항 실행 권한을 추가
before_install:
  - chmod +x ./gradlew

# Travis CI 서버의 Home
cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.gradle'

script: "./gradlew clean build"

# Travis CI에서 빌드하여 만든 Jar 파일을 S3에 올릴 수 있도록 하는 코드를 추가
# CodeDeploy는 JAR 파일을 인식하지 못하므로 zip 파일로 압축함 (본인의 프로젝트 이름:  myn)
before_deploy:
  - zip -r myn *
  - mkdir -p deploy
  - mv myn.zip deploy/myn.zip

# S3로 파일 업로드 혹은 CodeDeploy로 배포 등 외부 서비스와 연동될 행위들을 선언
deploy:
  - provider: s3
    access_key_id: $AWS_ACCESS_KEY        # Travis repo settings에 설정된 값
    secret_access_key: $AWS_SECRET_KEY    # Travis repo settings에 설정된 값
    bucket: myn-bucket              # S3 버킷
    region: ap-northeast-2
    skip_cleanup: true
    acl: private           # zip 파일 접근을 private으로
    local_dir: deploy   # before_deploy에서 생성한 디렉토리
    wait-until-deployed: true

  - provider: codedeploy
    access_key_id: $AWS_ACCESS_KEY        # Travis repo settings에 설정된 값
    secret_access_key: $AWS_SECRET_KEY    # Travis repo settings에 설정된 값
    bucket: myn-bucket              # S3 버킷
    key: myn.zip                    # 빌드 파일을 압축해서 전달
    bundle_type: zip
    application: myn-application     # CodeDeploy 애플리케이션 이름
    deployment_group: myn-application-group  # CodeDeploy 애플리케이션 그룹 이름
    region: ap-northeast-2
    wait-until-deployed: true

# CI 실행 완료 시 메일로 알람
#notifications:
#  email:
#    recipients:
#      - yeseong31@naver.com