language: java
jdk:
  - openjdk11

# 어느 branch에 push될 때 Travis CI를 실행할지 결정
branches:
  only:
    - master

# gradlew에 대항 실행 권한을 추가
before_install:
  - chmod +x ./gradlew

# Travis CI 서버의 Home
# Gradle을 통해 의존성을 받으면 이를 해당 디렉터리에 cache하여 같은 의존성은 다음 배포 때부터 다시 받지 않도록 설정
cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.gradle'

# master 브랜치에 Push되었을 때 수행하는 명령어
# 여기에서는 프로젝트 내부에 둔 gradlew 파일을 통해 clean & build를 수행
script: "./gradlew clean build"

# CI 실행 완료 시 메일로 알람
notifications:
  email:
    recipients:
      - yeseong31@naver.com