# version: CodeDeploy 버전. '프로젝트 버전'을 의미하지 않으므로 반드시 0.0으로 설정
# source: CodeDeploy에서 전달해 준 파일 중 destination으로 이동시킬 대상(전체 파일)
# destination: source에서 지정된 파일을 받을 위치

version: 0.0
os: linux
files:
  - source:  /
    destination: /home/ec2-user/app/step2/zip/
    overwrite: yes

# CodeDeploy에서 EC2 서버로 넘겨준 파일들을 모두 'ec2-user' 권한을 가지도록 함
permissions:
  - object: /
    pattern: "**"
    owner: ec2-user
    group: ec2-user

# CodeDeploy 배포 단계에서 실행할 명령어를 저장
# ApplicationStart 단계에서 deploy.sh를 'ec2-user' 권한으로 실행
hooks:
  ApplicationStart:
    - location: deploy.sh
      timeout: 60
      runas: ec2-user
